#if UNITY_EDITOR
using System.Linq;
using UnityEditor;

// Safety net: keeps the four scenes in Build Settings even if
// EditorBuildSettings.asset ever gets regenerated by the editor.
public static class BuildSettingsSync
{
    static readonly string[] Scenes =
    {
        "Assets/Scenes/Level1.unity",
        "Assets/Scenes/Level2.unity",
        "Assets/Scenes/Level3.unity",
        "Assets/Scenes/Celebration.unity",
    };

    [InitializeOnLoadMethod]
    static void Sync()
    {
        string[] current = EditorBuildSettings.scenes.Select(s => s.path).ToArray();
        if (!Scenes.All(current.Contains))
        {
            EditorBuildSettings.scenes =
                Scenes.Select(p => new EditorBuildSettingsScene(p, true)).ToArray();
        }
    }
}
#endif
